- debug:
    msg: "{{mirror_dir}} and {{download_url}}"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  loop:
  - "{{app_dir}}"
  - "{{mirror_dir}}"

- name: Download
  ansible.builtin.get_url:
    url: "{{download_url}}"
    dest: "{{mirror_dir}}/{{file_name}}"
    mode: '0755'

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{mirror_dir}}/{{file_name}}"
    dest: "{{app_dir}}/{{file_name}}"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    state: link

- name: Launcher - Desktop file
  ansible.builtin.template:
    src: beekeeper-studio.desktop.j2
    dest: "/home/{{ ansible_user }}/.local/share/applications/beekeeper-studio.desktop"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: true

# Do: I may have slight issues with Variables for include_role! Fix this!
- name: AppImage Dependencies
  ansible.builtin.include_role:
    name: AppImage

- name: AppImage Extract Icon
  ansible.builtin.include_role:
    name: AppImage/extract icon
