- debug:
    msg: "{{app_dir}}/{{file_name}}"

# - name: Run script extract-icon.sh
#   ansible.builtin.script: "extract-icon.sh {{file_name}}"
#   args:
#     chdir: "{{app_dir}}"
#     creates: /the/created/file.txt
#   become: true