- hosts: localhost
  vars:
    # Host_vars
    ansible_become_password: u
    ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"

  roles:
  - Beekeeper Studio

# Do: I may have slight issues with Variables for include_role! Fix!